CsStatTracker/Controllers/MembersController.cs
using CsStatTracker.Data;
using CsStatTracker.Models;
using Microsoft.AspNetCore.Mvc;

namespace CsStatTracker.Controllers
{
    public class MembersController : Controller
    {
        private readonly StatsContext _context;
        
        public MembersController(StatsContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel registerModel)
        {
            if (ModelState.IsValid)
            {
                Members newMember = new()
                {
                    Email = registerModel.Email,
                    Password = registerModel.Password,
                    UserName = registerModel.UserName,
                };
                _context.Members.Add(newMember);
                await _context.SaveChangesAsync();

                LogUserIn(newMember.Email);

                return RedirectToAction("Index", "Home");
            }
            
            return View(registerModel);
        }
        [HttpGet]
        public IActionResult Login() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(LoginViewModel loginModel) 
        {
            if (ModelState.IsValid)
            {
                Members? m = (from Members in _context.Members
                             where Members.Email == loginModel.Email
                             &&  Members.Password == loginModel.Password
                             select Members).SingleOrDefault();
                if (m != null)
                {
                    LogUserIn(loginModel.Email);
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError(string.Empty, "Invalid Username or password.");
            }
            return View(loginModel);
        }
        private void LogUserIn(string email)
        {
            HttpContext.Session.SetString("Email", email);
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var member = new Members
                {
                    UserName = model.UserName,
                    Email = model.Email,
                    Password = model.Password,
                    Phone = model.Phone,
                };

                _context.Members.Add(member); // Prepares insert
                await _context.SaveChangesAsync(); // Executes pending insert


                ViewData["Message"] = $"{member.UserName} was added successfully.";

                return View();
            }
            return View(model);
        }
    }
}

CsStatTracker/Controllers/StatsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RestSharp;
using Newtonsoft.Json;
using CsStatTracker.Models;



namespace CsStatTracker.Controllers
{
    

    public class ApiResponse
    {
       public Data Data { get; set; }
        
    }
    public class Data
    {
        public platformInfo platformInfo { get; set; }
        public List<Segments> Segments { get; set; }
        
    }
    public class StatsController : Controller
    {
        private readonly RestClient _client;
        private readonly string _trackerApiKey;
        private readonly ILogger _logger;


        public StatsController(IConfiguration configuration)
        {
            _trackerApiKey = configuration.GetSection("TrackerApiKeyUserSecret").Value;
            _client = new RestClient("https://public-api.tracker.gg/v2/csgo/standard/profile/");
        }

        public async Task<IActionResult> MemberStats(string steamId)
        {
            if (string.IsNullOrEmpty(_trackerApiKey))
            {
                return BadRequest("API key not found.");
            }

            var request = new RestRequest($"https://public-api.tracker.gg/v2/csgo/standard/profile/steam/{steamId}", Method.Get);
            request.AddHeader("TRN-Api-Key", _trackerApiKey);
            var response = await _client.ExecuteAsync(request);
            var content = JsonConvert.DeserializeObject<ApiResponse>(response.Content);
            

            var statsViewModel = new StatsViewModel();
            if(content.Data != null)
            {
                statsViewModel.SteamID = content.Data.platformInfo.platformUserId;
                statsViewModel.Username = content.Data.platformInfo.platformUserHandle;
                statsViewModel.Wins = content.Data.Segments[0].stats.wins.value;
                statsViewModel.Losses = content.Data.Segments[0].stats.losses.value;
                statsViewModel.WinRate = content.Data.Segments[0].stats.wlPercentage.value;
                statsViewModel.RoundsPlayed = content.Data.Segments[0].stats.roundsPlayed.value;
                statsViewModel.RoundsWon = content.Data.Segments[0].stats.roundsWon.value;
                statsViewModel.Damage = content.Data.Segments[0].stats.damage.value;
                statsViewModel.HeadShotPercent = content.Data.Segments[0].stats.headshotPct.value;
                

                
            };

            return View(statsViewModel);
        }







        public async Task<string> SearchPlayer(string playerName)
        {
            var request = new RestRequest("search", Method.Get);
            request.AddParameter("query", playerName);
            request.AddHeader("TRN-Api-Key", _trackerApiKey);
            var response = await _client.ExecuteAsync<SearchResult>(request);

            if (response.IsSuccessful && response.Data?.Data?.Any() == true)
            {
                return response.Data.Data[0].PlatformUserHandle;
            }

            return null;
        }

        public class SearchResult
        {
            public List<SearchResultData> Data { get; set; }
        }

        public class SearchResultData
        {
            public string PlatformUserHandle { get; set; }
        }

    }
}

CsStatTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CsStatTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CsStatTracker.styles.css" asp-append-version="true" />
    <style>
        body {
            background: linear-gradient(to bottom, #002147, #00091a);
            color: #fff;    
        }

        h2 {
            margin-top: 30px;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            max-width: 800px;
            margin-bottom: 30px;
        }

        th, td {
            padding: 10px;
            text-align: center;
        }

        .navbar {
            background-color: #337ab7; /* Lighter blue color */
        }

        .navbar-light .navbar-nav .nav-link {
            color: #fff;
            border-bottom-color: black;
            
        }
        .footer{
            border-top-color: black;
        }
        

    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CsStatTracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Members" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Members" asp-action="Login">Log in</a>
                        </li>
                    </ul>
                    <form class="d-flex" asp-area="" asp-controller="Stats" asp-action="MemberStats" method="get">
                        <input class="form-control me-2" type="search" placeholder="Search Steam ID" aria-label="Search" name="steamId">
                        <button id="searchId" class="btn btn-success btn-custom" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CsStatTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>